const container = document.getElementById("trends");

// List of trend data files (auto-generated by generate.py)
const TREND_FILES = [
  "ai_yearbook_photos.json",
  "girl_dinner.json",
  "npc_livestreams.json",
  "skull_emoji_era.json"
];

async function loadTrends() {
  container.innerHTML = "";

  const trends = [];

  for (const file of TREND_FILES) {
    try {
      const res = await fetch(`./data/${file}?ts=${Date.now()}`);
      const data = await res.json();
      trends.push(data);
    } catch (err) {
      console.error("Failed loading", file, err);
    }
  }

  // Sort by total interest (descending)
  trends.sort((a, b) => getTotalInterest(b) - getTotalInterest(a));

  trends.forEach(renderTrend);
}

function getTotalInterest(data) {
  const m = data.metrics || {};
  const g = data.google_trends || {};
  return (
    (m.tiktok || 0) +
    (m.youtube || 0) +
    (m.x || 0) +
    (g.interest_score || 0)
  );
}

function renderTrend(data) {
  const card = document.createElement("div");
  card.className = "card";

  const status = data.analysis?.status || "stable";
  const metrics = data.metrics || {};
  const google = data.google_trends || {};

  const total = getTotalInterest(data);

  // ----- IMAGE (SAFE) -----
  const imagePrompt = data.analysis?.image_prompt || data.trend;
  const imageUrl = `https://source.unsplash.com/900x500/?${encodeURIComponent(
    imagePrompt
  )}`;

  const img = document.createElement("img");
  img.className = "trend-image";
  img.style.display = "none";
  img.src = imageUrl;

  img.onload = () => (img.style.display = "block");
  img.onerror = () => img.remove();

  card.appendChild(img);

  // ----- CONTENT -----
  card.innerHTML += `
    <h2>${data.trend}</h2>

    <div class="status ${status}">
      ${status.toUpperCase()}
    </div>

    <p>${data.analysis?.analysis || ""}</p>

    <div class="meme">
      😂 ${data.analysis?.meme || ""}
    </div>

    <div class="counters">
      <div class="total">
        👀 <strong>Total Interest:</strong> ${total}
      </div>
      <div class="counter-row">
        <span>🎵 TikTok: ${metrics.tiktok || 0}</span>
        <span>▶️ YouTube: ${metrics.youtube || 0}</span>
        <span>🐦 X: ${metrics.x || 0}</span>
        <span>🔎 Google: ${google.interest_score || 0}</span>
      </div>
    </div>
  `;

  // Optional token section
  if (data.token) {
    card.innerHTML += `
      <div class="token">
        🪙 <strong>${data.token.ticker}</strong> (${data.token.chain})<br/>
        Liquidity: $${data.token.liquidity?.toLocaleString() || 0}<br/>
        1h Volume: $${data.token.volume_1h?.toLocaleString() || 0}
      </div>
    `;
  }

  container.appendChild(card);
}

// Initial load + auto refresh
loadTrends();
setInterval(loadTrends, 120000);
